### PR TITLE
Earnings report cookbook

### PR DESCRIPTION
**Pull request by cpfiffer**
This is a condensed version of the demo for [extracting earnings reports](https://github.com/dottxt-ai/demos/tree/main/earnings-reports) to CSV. 

Overview:

- Shows how to use Outlines to structure CSV output
- Provides simple tools for converting a table specification to regular expressions
- Includes a tuned extraction prompt that performs reasonably well on income statements

### CODE REVIEW

**Comment by rlouf** [comment]
Is this ready for review?

**Comment by cpfiffer** [comment]
Yes, sorry!

**Comment by cpfiffer** [comment]
Could I get a bump on this one? Need to start linking to it.

**Review by willkurt — APPROVED** [review]
LGTM!

**Review by willkurt — APPROVED** [review]

**Pull request merged**
