### PR TITLE
Add json call with multi-function enums

### PR DESCRIPTION
**Pull request by g-prz**
This PR aims at solving #1217

### CODE REVIEW

**Comment by g-prz** [comment]
Hey @rlouf 🙋‍♂️ 
By any chance, do you have a PR template? 
Otherwise ready for review

**Comment by g-prz** [comment]
Hey @rlouf 
Just fixed the [failing test](https://github.com/dottxt-ai/outlines/actions/runs/12007321695/job/33610120278), but seems there is an issue with a HF token? Is this known?

**Comment by rlouf** [comment]
I just realized this. They actually removed one of the models we used for testing, will fix that in another PR.

**Comment by rlouf** [comment]
Rebased the branch and changed the commit name to follow the repo's conventions.

**Pull request merged**
