### PR TITLE
Add docs on serving with LM Studio

### PR DESCRIPTION
**Pull request by cpfiffer**
Adds docs to get people up and running with the LM Studio structured generation endpoint.

### CODE REVIEW

**Comment by rlouf** [comment]
Thanks! Please run `pre-commit` :)

**Comment by rlouf** [comment]
@cpfiffer

**Comment by cpfiffer** [comment]
Well, that's a cool tool!

**Comment by rlouf** [comment]
We forgot to link to it in the docs! Could you open another PR?

**Pull request merged**
